{% set name = "rocket-fft" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/styfenschaer/rocket-fft/archive/v{{ version }}.tar.gz
  sha256: 13915b9e70909589bd0301ea79c465de1c6d80ea69d015a0b3f41c8c1caf0fe7

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - numba >=0.56.0
    - numpy
    - pip
    - python
    - setuptools >=59.2.0
  run:
    - numba >=0.56.0
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - rocket_fft
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/rocket-fft
  summary: Rocket-FFT extends Numba by scipy.fft and numpy.fft
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/styfenschaer/rocket-fft

extra:
  recipe-maintainers:
    - goanpeca
